# Generated by Django 4.2 on 2023-04-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=46)),
                ("content", models.TextField()),
                ("post_date", models.DateTimeField(verbose_name="date published")),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
    ]
