# Generated by Django 4.2 on 2023-04-12 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_post_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="user_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
