# Generated by Django 4.2 on 2023-04-12 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_friend_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="follower",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="my_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="my_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
