# Generated by Django 4.2 on 2023-04-13 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="likes",),
        migrations.DeleteModel(name="Likes",),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
